### ISSUE TITLE
Problem, may be caused by the use of a VM ?

### ISSUE THREAD

**Issue by Madcat-76310** [Xorfor/Domoticz-PWS-Plugin#17]
Hi,
I'm using the plugin on a raspberry, all is ok, but now i'm using a Freebox Delta Server, with a Virtual Machine (Debian Bullseye) and i 've a problem that i don't understand :

2022-11-07 15:09:48.895 Station Météo: Worker thread started.
2022-11-07 15:09:48.979 Station Météo: Debug logging mask set to: NONE
2022-11-07 15:09:48.895 Status: Station Météo: Entering work loop.
2022-11-07 15:09:48.895 Status: Station Météo: Started.
2022-11-07 15:09:48.973 Status: Station Météo: Initialized version 1.2.2, author 'Xorfor'
2022-11-07 15:09:53.990 Error: Station Météo: Call to function 'onMessage' failed, exception details:
2022-11-07 15:09:54.008 Error: Station Météo: Traceback (most recent call last):
2022-11-07 15:09:54.008 Error: Station Météo: File "/home/freebox/domoticz/plugins/Domoticz-PWS-Plugin/plugin.py", line 487, in onMessage
2022-11-07 15:09:54.008 Error: Station Météo: _plugin.onMessage(Connection, Data)
2022-11-07 15:09:54.008 Error: Station Météo: File "/home/freebox/domoticz/plugins/Domoticz-PWS-Plugin/plugin.py", line 314, in onMessage
2022-11-07 15:09:54.008 Error: Station Météo: pm25 = round(pm25, 1) if pm25 is not None else None
2022-11-07 15:09:54.008 Error: Station Météo: UnboundLocalError: local variable 'pm25' referenced before assignment

May be an idea ?
Regards

**Comment by Xorfor** [comment]
I think it is NOT your VM. Recently I implemented new sensors for WH45. These were implemented for Ecowitt protocol. I guess that you are using the Wunderground protocol. I fixed this, but I am not able to test this.
Please use the latest version 1.2.3

**Comment by Madcat-76310** [comment]
Ok, i'll try new version and/or Ecowitt tonight. I'm using Underground, PWS : ISAINT2425
Thank you, regards

**Comment by Xorfor** [comment]
Don't switch the protocol, that is not needed. Just use the latest plugin version.

**Comment by Madcat-76310** [comment]
With the lastest plugin version, nothing happens : 

2022-11-07 21:05:40.730 Status: ISAINT2425: Started.
2022-11-07 21:05:40.807 Status: ISAINT2425: Initialized version 1.2.3, author 'Xorfor'
2022-11-07 21:05:50.032 ISAINT2425: Pushing 'onHeartbeatCallback' on to queue
2022-11-07 21:05:50.082 ISAINT2425: Processing 'onHeartbeatCallback' message
2022-11-07 21:05:50.082 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:05:50.082 ISAINT2425: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-07 21:05:50.082 ISAINT2425: onHeartbeat
2022-11-07 21:05:50.082 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:05:51.818 Status: Incoming connection from: 127.0.0.1
2022-11-07 21:06:00.006 ISAINT2425: Pushing 'onHeartbeatCallback' on to queue
2022-11-07 21:06:00.056 ISAINT2425: Processing 'onHeartbeatCallback' message
2022-11-07 21:06:00.056 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:06:00.056 ISAINT2425: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-07 21:06:00.056 ISAINT2425: onHeartbeat
2022-11-07 21:06:00.056 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:06:10.025 ISAINT2425: Pushing 'onHeartbeatCallback' on to queue
2022-11-07 21:06:10.075 ISAINT2425: Processing 'onHeartbeatCallback' message
2022-11-07 21:06:10.075 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:06:10.075 ISAINT2425: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-07 21:06:10.075 ISAINT2425: onHeartbeat
2022-11-07 21:06:10.075 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:06:20.044 ISAINT2425: Pushing 'onHeartbeatCallback' on to queue
2022-11-07 21:06:20.094 ISAINT2425: Processing 'onHeartbeatCallback' message
2022-11-07 21:06:20.094 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:06:20.094 ISAINT2425: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-07 21:06:20.094 ISAINT2425: onHeartbeat
2022-11-07 21:06:20.094 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:06:30.015 ISAINT2425: Pushing 'onHeartbeatCallback' on to queue
2022-11-07 21:06:30.065 ISAINT2425: Processing 'onHeartbeatCallback' message
2022-11-07 21:06:30.065 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:06:30.065 ISAINT2425: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-07 21:06:30.065 ISAINT2425: onHeartbeat
2022-11-07 21:06:30.065 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:06:40.035 ISAINT2425: Pushing 'onHeartbeatCallback' on to queue
2022-11-07 21:06:40.085 ISAINT2425: Processing 'onHeartbeatCallback' message
2022-11-07 21:06:40.085 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:06:40.085 ISAINT2425: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-07 21:06:40.085 ISAINT2425: onHeartbeat
2022-11-07 21:06:40.085 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:06:50.007 ISAINT2425: Pushing 'onHeartbeatCallback' on to queue
2022-11-07 21:06:50.057 ISAINT2425: Processing 'onHeartbeatCallback' message
2022-11-07 21:06:50.057 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:06:50.057 ISAINT2425: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-07 21:06:50.057 ISAINT2425: onHeartbeat
2022-11-07 21:06:50.058 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:07:00.030 ISAINT2425: Pushing 'onHeartbeatCallback' on to queue
2022-11-07 21:07:00.080 ISAINT2425: Processing 'onHeartbeatCallback' message
2022-11-07 21:07:00.080 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:07:00.080 ISAINT2425: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-07 21:07:00.080 ISAINT2425: onHeartbeat
2022-11-07 21:07:00.081 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:07:10.052 ISAINT2425: Pushing 'onHeartbeatCallback' on to queue
2022-11-07 21:07:10.102 ISAINT2425: Processing 'onHeartbeatCallback' message
2022-11-07 21:07:10.102 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:07:10.102 ISAINT2425: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-07 21:07:10.102 ISAINT2425: onHeartbeat
2022-11-07 21:07:10.102 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:07:20.021 ISAINT2425: Pushing 'onHeartbeatCallback' on to queue
2022-11-07 21:07:20.071 ISAINT2425: Processing 'onHeartbeatCallback' message
2022-11-07 21:07:20.071 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:07:20.071 ISAINT2425: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-07 21:07:20.071 ISAINT2425: onHeartbeat
2022-11-07 21:07:20.072 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:07:30.043 ISAINT2425: Pushing 'onHeartbeatCallback' on to queue
2022-11-07 21:07:30.093 ISAINT2425: Processing 'onHeartbeatCallback' message
2022-11-07 21:07:30.093 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:07:30.093 ISAINT2425: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-07 21:07:30.093 ISAINT2425: onHeartbeat
2022-11-07 21:07:30.093 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:07:40.016 ISAINT2425: Pushing 'onHeartbeatCallback' on to queue
2022-11-07 21:07:40.066 ISAINT2425: Processing 'onHeartbeatCallback' message
2022-11-07 21:07:40.066 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:07:40.066 ISAINT2425: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-07 21:07:40.066 ISAINT2425: onHeartbeat
2022-11-07 21:07:40.066 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:07:50.040 ISAINT2425: Pushing 'onHeartbeatCallback' on to queue
2022-11-07 21:07:50.090 ISAINT2425: Processing 'onHeartbeatCallback' message
2022-11-07 21:07:50.090 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:07:50.090 ISAINT2425: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-07 21:07:50.090 ISAINT2425: onHeartbeat
2022-11-07 21:07:50.090 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:08:00.011 ISAINT2425: Pushing 'onHeartbeatCallback' on to queue
2022-11-07 21:08:00.061 ISAINT2425: Processing 'onHeartbeatCallback' message
2022-11-07 21:08:00.061 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:08:00.062 ISAINT2425: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-07 21:08:00.062 ISAINT2425: onHeartbeat
2022-11-07 21:08:00.062 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:08:10.032 ISAINT2425: Pushing 'onHeartbeatCallback' on to queue
2022-11-07 21:08:10.082 ISAINT2425: Processing 'onHeartbeatCallback' message
2022-11-07 21:08:10.082 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:08:10.082 ISAINT2425: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-07 21:08:10.082 ISAINT2425: onHeartbeat
2022-11-07 21:08:10.082 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:08:20.003 ISAINT2425: Pushing 'onHeartbeatCallback' on to queue
2022-11-07 21:08:20.053 ISAINT2425: Processing 'onHeartbeatCallback' message
2022-11-07 21:08:20.053 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'
2022-11-07 21:08:20.053 ISAINT2425: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-07 21:08:20.053 ISAINT2425: onHeartbeat
2022-11-07 21:08:20.053 ISAINT2425: Acquiring GIL for 'onHeartbeatCallback'

**Comment by Madcat-76310** [comment]
And after a good send of datas, it's not working again... I'll try with ecowitt

**Comment by Madcat-76310** [comment]
I can't use Ecowitt with Domoticz.
With WU, it's look like there sone send of datas and only after error message and no transmission.

**Comment by Xorfor** [comment]
Can you give me some information, about:

1. hardware
2. domoticz version
3. please switch debug on true and give me some logging where the received json is visible. See previous issue.
4. Which WS View firmware version is used?

It looks like the data you receive from your PWS is not what I expect.

**Comment by Madcat-76310** [comment]
Hi, i must working (24 hours watch), i'll give you all information in 36 hours, thank you for your help. regards

**Comment by Madcat-76310** [comment]
Hi, new information : it's working well (36 hours without problem), i've made nothing except using the "WSView Plus" instead "WSView" on my iPhone, and making a reset of the PWS. I thing it was the problem.
So, your plugin is stable, i close the issue.
Thank you very much for your support ! Best Regards
